version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_DB=simple_bank
      - POSTGRES_PASSWORD=secret1
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret1@loslhost:5431/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
    


# Run: docker compose up
# Run: docker network inspect